# Generated by Django 2.0 on 2018-01-09 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='read',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
