# Generated by Django 2.0 on 2018-01-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timework', '0002_messages_read'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
